import Foundation

// MARK: - Stamp Image Mapping
// Maps ISO 3166-1 alpha-2 country codes to landmark stamp image names in Assets.xcassets/Stamps/
// 187 unique countries, 216 total landmark images

enum StampImageMapping {

    // MARK: - Primary Stamp (one per country)

    static let primaryStamp: [String: String] = [
        "AD": "Stamps/Andorra la Vella Old Town",
        "AE": "Stamps/Burj Khalifa",
        "AF": "Stamps/Band‑e Amir Lakes in Afghanistan",
        "AG": "Stamps/Dickenson Bay",
        "AL": "Stamps/Ksamil Beach in Albania",
        "AM": "Stamps/Geghard Monastery in Armenia",
        "AO": "Stamps/Miradouro da Lua in Angola",
        "AR": "Stamps/Iguazu Falls",
        "AT": "Stamps/Hallstatt village and lake",
        "AU": "Stamps/Sydney Opera House",
        "AZ": "Stamps/Maiden Tower in Baku, Azerbaijan",
        "BA": "Stamps/Stari Most bridge in Mostar",
        "BB": "Stamps/Bathsheba Beach in Barbados",
        "BD": "Stamps/National Parliament House in Dhaka",
        "BF": "Stamps/Burkina Faso — Ruins of Loropéni",
        "BG": "Stamps/Rila Monastery in Bulgaria",
        "BH": "Stamps/Bahrain Fort (Qal’at al‑Bahrain)",
        "BI": "Stamps/Burundi — Lake Tanganyika",
        "BJ": "Stamps/Royal Palaces of Abomey in Benin",
        "BN": "Stamps/Omar Ali Saifuddien Mosque in Brunei",
        "BO": "Stamps/Salar de Uyuni salt flats in Bolivia",
        "BR": "Stamps/Christ the Redeemer in Rio de Janeiro",
        "BS": "Stamps/Exuma Cays",
        "BT": "Stamps/Tiger’s Nest Monastery in Bhutan",
        "BW": "Stamps/Okavango Delta in Botswana",
        "BY": "Stamps/Mir Castle in Belarus",
        "BZ": "Stamps/the Great Blue Hole in Belize",
        "CA": "Stamps/Moraine Lake in Canada",
        "CD": "Stamps/Virunga National Park in the Democratic Republic of the Congo",
        "CF": "Stamps/Orta Afrika Cumhuriyeti — Dzanga‑Sangha Rainforest",
        "CG": "Stamps/Kongo Cumhuriyeti — Congo River (Brazzaville)",
        "CH": "Stamps/Matterhorn mountain",
        "CI": "Stamps/Basilica of Our Lady of Peace in Yamoussoukro",
        "CL": "Stamps/Torres del Paine National Park in Chile",
        "CM": "Stamps/Mount Cameroon",
        "CN": "Stamps/Great Wall of China",
        "CO": "Stamps/Old Town of Cartagena",
        "CR": "Stamps/Arenal Volcano in Costa Rica",
        "CU": "Stamps/Old Havana (Habana Vieja)",
        "CV": "Stamps/Fogo Volcano in Cape Verde",
        "CY": "Stamps/Nissi Beach in Cyprus",
        "CZ": "Stamps/Charles Bridge in Prague",
        "DE": "Stamps/Neuschwanstein Castle",
        "DJ": "Stamps/Cibuti — Lake Assal",
        "DK": "Stamps/Nyhavn harbor in Copenhagen",
        "DM": "Stamps/Dominika — Boiling Lake",
        "DO": "Stamps/Punta Cana beach in the Dominican Republic",
        "DZ": "Stamps/Tassili n’Ajjer in Algeria",
        "EC": "Stamps/Galápagos Islands in Ecuador",
        "EE": "Stamps/Tallinn Old Town",
        "EG": "Stamps/Pyramids of Giza",
        "ER": "Stamps/Asmara Modernist Architecture",
        "ES": "Stamps/Sagrada Familia in Barcelona",
        "ET": "Stamps/Rock‑Hewn Churches of Lalibela in Ethiopia",
        "FI": "Stamps/Helsinki Cathedral",
        "FJ": "Stamps/Mamanuca Islands in Fiji",
        "FM": "Stamps/Nan Madol ruins in Micronesia",
        "FR": "Stamps/Eiffel Tower",
        "GA": "Stamps/Loango National Park",
        "GB": "Stamps/Big Ben in London",
        "GD": "Stamps/Grand Anse Beach",
        "GE": "Stamps/Gergeti Trinity Church in Georgia",
        "GH": "Stamps/Cape Coast Castle in Ghana",
        "GM": "Stamps/Gambia River",
        "GN": "Stamps/the Fouta Djallon Highlands",
        "GQ": "Stamps/Ekvator Ginesi — Bioko Island Coast",
        "GR": "Stamps/Acropolis of Athens",
        "GT": "Stamps/Tikal ruins in Guatemala",
        "GW": "Stamps/the Bijagós Archipelago",
        "GY": "Stamps/Guyana — Kaieteur Falls",
        "HK": "Stamps/Victoria Harbour skyline in Hong Kong",
        "HN": "Stamps/Honduras — Copán Ruins",
        "HR": "Stamps/Old City of Dubrovnik",
        "HT": "Stamps/Haiti — Citadelle Laferrière",
        "HU": "Stamps/Hungarian Parliament Building in Budapest",
        "ID": "Stamps/Borobudur Temple in Indonesia",
        "IE": "Stamps/Cliffs of Moher in Ireland",
        "IL": "Stamps/Old City of Jerusalem",
        "IN": "Stamps/India — Taj Mahal",
        "IQ": "Stamps/Erbil Citadel in Iraq",
        "IR": "Stamps/Iran — Nasir al‑Molk Mosque",
        "IS": "Stamps/Kirkjufell mountain in Iceland",
        "IT": "Stamps/Colosseum in Rome",
        "JM": "Stamps/Jamaica — Dunn’s River Falls",
        "JO": "Stamps/Petra in Jordan",
        "JP": "Stamps/Mount Fuji",
        "KE": "Stamps/Maasai Mara savannah in Kenya",
        "KG": "Stamps/Ala‑Archa National Park in Kyrgyzstan",
        "KH": "Stamps/Angkor Wat in Cambodia",
        "KI": "Stamps/Kiribati — Tarawa Lagoon",
        "KM": "Stamps/Komorlar — Mount Karthala",
        "KP": "Stamps/Ryugyong Hotel in Pyongyang, North Korea",
        "KR": "Stamps/Gyeongbokgung Palace in Seoul",
        "KW": "Stamps/Kuwait Towers",
        "KZ": "Stamps/Bayterek Tower in Astana",
        "LA": "Stamps/Kuang Si Falls in Laos",
        "LB": "Stamps/Baalbek Roman Ruins in Lebanon",
        "LC": "Stamps/Saint Lucia — Pitons",
        "LI": "Stamps/Vaduz Castle in Liechtenstein",
        "LK": "Stamps/Sigiriya Rock Fortress in Sri Lanka",
        "LR": "Stamps/Liberia — Robertsport Coast",
        "LS": "Stamps/Lesotho — Maletsunyane Falls",
        "LT": "Stamps/Trakai Island Castle in Lithuania",
        "LU": "Stamps/Old Town and Fortifications of Luxembourg",
        "LV": "Stamps/Riga Old Town",
        "LY": "Stamps/Libya — Leptis Magna",
        "MA": "Stamps/Marrakech Medina",
        "MC": "Stamps/Monte Carlo Casino in Monaco",
        "MD": "Stamps/Orheiul Vechi in Moldova",
        "ME": "Stamps/Kotor Old Town",
        "MG": "Stamps/Avenue of the Baobabs in Madagascar",
        "MH": "Stamps/Marshall Islands — Majuro Atoll",
        "MK": "Stamps/Lake Ohrid in North Macedonia",
        "ML": "Stamps/Great Mosque of Djenné in Mali",
        "MM": "Stamps/Bagan temple plains in Myanmar",
        "MN": "Stamps/Flaming Cliffs in the Gobi Desert, Mongolia",
        "MR": "Stamps/Mauritania — Eye of the Sahara",
        "MT": "Stamps/Blue Lagoon in Comino, Malta",
        "MU": "Stamps/Le Morne Brabant in Mauritius",
        "MV": "Stamps/overwater bungalows in the Maldives",
        "MW": "Stamps/Malawi — Lake Malawi",
        "MX": "Stamps/Chichen Itza",
        "MY": "Stamps/Petronas Twin Towers in Kuala Lumpur",
        "MZ": "Stamps/Bazaruto Archipelago in Mozambique",
        "NA": "Stamps/Sossusvlei dunes in Namibia",
        "NE": "Stamps/Agadez Grand Mosque in Niger",
        "NG": "Stamps/Zuma Rock in Nigeria",
        "NI": "Stamps/Nicaragua — Ometepe Island",
        "NL": "Stamps/Amsterdam canal houses and bridges",
        "NO": "Stamps/Geirangerfjord in Norway",
        "NP": "Stamps/Mount Everest in Nepal",
        "NR": "Stamps/Anibare Bay in Nauru",
        "NZ": "Stamps/Milford Sound in New Zealand",
        "OM": "Stamps/Wadi Shab in Oman",
        "PA": "Stamps/Panama Canal",
        "PE": "Stamps/Machu Picchu in Peru",
        "PG": "Stamps/Kokoda Track highlands in Papua New Guinea",
        "PH": "Stamps/Chocolate Hills in the Philippines",
        "PK": "Stamps/Badshahi Mosque in Lahore",
        "PL": "Stamps/Old Town Square in Warsaw",
        "PT": "Stamps/Lisbon tram in Alfama",
        "PW": "Stamps/Rock Islands in Palau",
        "PY": "Stamps/Itaipú Dam in Paraguay",
        "QA": "Stamps/Qatar — Museum of Islamic Art",
        "RO": "Stamps/Bran Castle in Romania",
        "RS": "Stamps/Belgrade Fortress",
        "RU": "Stamps/Saint Basil’s Cathedral",
        "RW": "Stamps/Volcanoes National Park in Rwanda",
        "SA": "Stamps/Al‑Ula (Hegra) in Saudi Arabia",
        "SB": "Stamps/Marovo Lagoon in the Solomon Islands",
        "SC": "Stamps/Anse Source d’Argent beach in Seychelles",
        "SD": "Stamps/Sudan — Meroë Pyramids",
        "SE": "Stamps/Stockholm Old Town (Gamla Stan)",
        "SG": "Stamps/Marina Bay Sands in Singapore",
        "SI": "Stamps/Lake Bled",
        "SK": "Stamps/Bratislava Castle in Slovakia",
        "SL": "Stamps/River Number Two Beach in Sierra Leone",
        "SM": "Stamps/Guaita Tower in San Marino",
        "SN": "Stamps/Gorée Island in Senegal",
        "SR": "Stamps/Suriname — Central Suriname Nature Reserve",
        "SS": "Stamps/South Sudan — White Nile Wetlands",
        "ST": "Stamps/São Tomé and Príncipe — Pico Cão Grande",
        "SV": "Stamps/El Salvador — Santa Ana Volcano",
        "SY": "Stamps/Krak des Chevaliers in Syria",
        "SZ": "Stamps/Mlilwane Wildlife Sanctuary",
        "TD": "Stamps/Çad — Ennedi Plateau",
        "TG": "Stamps/Togoville on Lake Togo",
        "TH": "Stamps/Wat Arun in Bangkok",
        "TJ": "Stamps/Pamir Mountains in Tajikistan",
        "TL": "Stamps/Atauro Island in Timor‑Leste",
        "TM": "Stamps/Darvaza Gas Crater in Turkmenistan",
        "TN": "Stamps/El Djem Amphitheatre in Tunisia",
        "TO": "Stamps/Haʻamonga ʻa Maui trilithon in Tonga",
        "TR": "Stamps/Turkey — Cappadocia",
        "TV": "Stamps/Tuvalu — Funafuti Lagoon",
        "TW": "Stamps/Taipei 101 in Taiwan",
        "TZ": "Stamps/Mount Kilimanjaro",
        "UA": "Stamps/Saint Sophia Cathedral in Kyiv, Ukraine",
        "UG": "Stamps/Lake Bunyonyi in Uganda",
        "US": "Stamps/Statue of Liberty",
        "UY": "Stamps/Colonia del Sacramento in Uruguay",
        "UZ": "Stamps/Registan Square in Samarkand",
        "VA": "Stamps/St. Peter’s Basilica in Vatican City",
        "VC": "Stamps/Saint Vincent and the Grenadines — Tobago Cays",
        "VE": "Stamps/Angel Falls in Venezuela",
        "VN": "Stamps/Ha Long Bay in Vietnam",
        "VU": "Stamps/Mount Yasur Volcano in Vanuatu",
        "WS": "Stamps/To Sua Ocean Trench in Samoa",
        "XK": "Stamps/Prizren Old Town in Kosovo",
        "YE": "Stamps/Old City of Sana’a in Yemen",
        "ZA": "Stamps/Table Mountain in Cape Town",
        "ZM": "Stamps/Victoria Falls from the Zambian side",
        "ZW": "Stamps/Victoria Falls in Zimbabwe",
    ]

    // MARK: - All Stamps (countries with multiple landmarks)

    static let allStamps: [String: [String]] = [
        "AE": ["Stamps/Burj Khalifa", "Stamps/Dubai Marina skyline", "Stamps/Dubai desert dunes", "Stamps/Palm Jumeirah"],
        "AT": ["Stamps/Hallstatt village and lake", "Stamps/Vienna State Opera"],
        "AU": ["Stamps/Great Barrier Reef", "Stamps/Sydney Opera House"],
        "CH": ["Stamps/Chapel Bridge in Lucerne", "Stamps/Matterhorn mountain"],
        "CN": ["Stamps/Forbidden City in Beijing", "Stamps/Great Wall of China"],
        "DE": ["Stamps/Brandenburg Gate in Berlin", "Stamps/Neuschwanstein Castle"],
        "ES": ["Stamps/Park Güell in Barcelona", "Stamps/Sagrada Familia in Barcelona"],
        "FR": ["Stamps/Eiffel Tower", "Stamps/Louvre Museum", "Stamps/Mont Saint‑Michel"],
        "GB": ["Stamps/Big Ben in London", "Stamps/Edinburgh Castle", "Stamps/London Eye"],
        "GR": ["Stamps/Acropolis of Athens", "Stamps/Santorini white cliffside houses and blue domes"],
        "ID": ["Stamps/Bali Gate at Lempuyang or Handara", "Stamps/Borobudur Temple in Indonesia"],
        "IT": ["Stamps/Colosseum in Rome", "Stamps/Leaning Tower of Pisa"],
        "JP": ["Stamps/Mount Fuji", "Stamps/Tokyo Tower"],
        "KR": ["Stamps/Gyeongbokgung Palace in Seoul", "Stamps/Seoul skyline with Namsan Tower"],
        "PT": ["Stamps/Belém Tower in Lisbon", "Stamps/Lisbon tram in Alfama"],
        "MX": ["Stamps/Chichen Itza", "Stamps/Mexico City Metropolitan Cathedral"],
        "TH": ["Stamps/Phuket tropical beach", "Stamps/Wat Arun in Bangkok"],
        "US": ["Stamps/Golden Gate Bridge", "Stamps/Grand Canyon", "Stamps/Statue of Liberty"],
    ]

    // MARK: - Lookup Helpers

    /// Returns the primary stamp image asset name for a country code
    static func stampImageName(for countryCode: String) -> String? {
        primaryStamp[countryCode]
    }

    /// Returns all available stamp image asset names for a country code
    static func allStampImageNames(for countryCode: String) -> [String] {
        allStamps[countryCode] ?? (primaryStamp[countryCode].map { [$0] } ?? [])
    }

    /// Returns true if a custom stamp image exists for the given country code
    static func hasStampImage(for countryCode: String) -> Bool {
        primaryStamp[countryCode] != nil
    }
}
